# Site settings
title: Perfil personal
description: Una breve descripción de la vida de Osmar Castillo
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Osmar Alejandro Castillo Lancheros
user_description: Estudiante de Ingeniería de Sistemas y computación de la Universidad Nacional de Colombia, desarrollador apasionado, que disfruta de la música (reggae, rock, pero en general la música que viene del alma) y el café; busca promover las tecnologías libres y los derechos digitales.
user_title: Software Developer
email: oacastillol@gmail.com
twitter_username: oacastillol
github_username:  oacastillol

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
